name: Fetch Files from passcro

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'  # 每4小时运行一次

jobs:
  fetch_files:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.x'

    - name: Install dependencies
      run: |
        pip install requests pyyaml

    - name: Fetch files from passcro
      run: |
        import requests
        import yaml
        import json

        # GitHub 项目的 URL
        repo_url = "https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/"

        # 文件列表
        files = {
            "speednodes.yaml": "speednodes.yaml",
            "speednodes.txt": "speednodes.txt",
            "sing-box.json": "sing-box.json",
            "meta.yaml": "meta.yaml"
        }

        for file_name, file_path in files.items():
            response = requests.get(repo_url + file_name)
            if response.status_code == 200:
                with open(file_path, 'w') as f:
                    if file_name.endswith('.yaml'):
                        yaml.dump(yaml.safe_load(response.text), f)
                    elif file_name.endswith('.json'):
                        json.dump(response.json(), f, indent=4)
                    else:
                        f.write(response.text)
            else:
                print(f"Failed to fetch {file_name}: {response.status_code}")

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@gmail.com"
        git config --local user.name "GitHub Action"
        git add speednodes.yaml speednodes.txt sing-box.json meta.yaml
        git commit -m "Fetch latest files from passcro" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
